# Generated by Django 6.0.3 on 2026-04-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='career_role',
            field=models.CharField(choices=[('software_engineer', 'Software Engineer'), ('data_scientist', 'Data Scientist'), ('data_engineer', 'Data Engineer'), ('product_manager', 'Product Manager'), ('project_manager', 'Project Manager'), ('management', 'Management'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('design', 'Design')], default='software_engineer', help_text='Detected or user-selected career role for fair scoring', max_length=50),
        ),
    ]
