# Generated by Django 6.0.3 on 2026-04-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_career_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
