# Generated by Django 6.0.3 on 2026-04-01 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_entry', to='resume.resume')),
            ],
        ),
    ]
